const posterProducts = [
  {
    id: 1,
    name: "Caramelos Ghibbbli",
    image: "img/caramelos.jpg",
    description: "Caramelos varios.",
    price: 10,
    stock: 20,
  },
  {
    id: 2,
    name: "Turron de Dragon",
    image: "img/patatas.jpg",
    description: "Turron de chocolate.",
    price: 5,
    stock: 50,
  },
  {
    id: 3,
    name: "Tarta del Bosque Encantado",
    image: "./assets/products/tarta_bosque.jpeg",
    description: "Tarta mágica con ingredientes del bosque.",
    price: 12,
    stock: 15,
  },
  {
    id: 4,
    name: "Helado del Valle Misterioso",
    image: "img/helado_valle.jpg",
    description: "Helado suave con un toque de misterio.",
    price: 8,
    stock: 25,
  },
  {
    id: 5,
    name: "Poción de Energía Solar",
    image: "img/pocion_solar.jpg",
    description: "Bebida revitalizante hecha con rayos de sol.",
    price: 9,
    stock: 30,
  },
  /* {
    id: 6,
    name: "Sopa de la Estrella Fugaz",
    image: "img/sopa_estrella.jpg",
    description: "Caldo reconfortante inspirado en las estrellas.",
    price: 7,
    stock: 20,
  },
  {
    id: 7,
    name: "Empanada de la Luna Llena",
    image: "img/empanada_luna.jpg",
    description: "Empanada con un toque especial de noche mágica.",
    price: 6,
    stock: 40,
  },
  {
    id: 8,
    name: "Caramelos del Arcoíris",
    image: "img/caramelos_arcoiris.jpg",
    description: "Dulces coloridos que brillan al sol.",
    price: 4,
    stock: 50,
  },
  {
    id: 9,
    name: "Pizza del Dragón Legendario",
    image: "img/pizza_dragon.jpg",
    description: "Pizza con un sabor explosivo y aventurero.",
    price: 15,
    stock: 10,
  },
  {
    id: 10,
    name: "Pan de las Montañas Nebulosas",
    image: "img/pan_montanas.jpg",
    description: "Pan fresco con un aroma que inspira calma.",
    price: 5,
    stock: 25,
  },
  {
    id: 11,
    name: "Té del Espíritu Serpentino",
    image: "img/te_espiritu.jpg",
    description: "Infusión cálida con un toque de magia antigua.",
    price: 6,
    stock: 35,
  },
  {
    id: 12,
    name: "Galletas del Espantapájaros",
    image: "img/galletas_espantapajaros.jpg",
    description: "Galletas con un toque misterioso y divertido.",
    price: 7,
    stock: 50,
  },
  {
    id: 13,
    name: "Zumo del Árbol Viviente",
    image: "img/zumo_arbol.jpg",
    description: "Zumo fresco con sabores mágicos del bosque.",
    price: 10,
    stock: 30,
  },
  {
    id: 14,
    name: "Bombones del Castillo Mágico",
    image: "./assets/bombones_castillo.jpeg",
    description: "Chocolates con un diseño inspirado en castillos.",
    price: 14,
    stock: 12,
  },
  {
    id: 15,
    name: "Refresco del Viento Silbador",
    image: "img/refresco_viento.jpg",
    description: "Bebida gaseosa que refresca como una brisa.",
    price: 9,
    stock: 20,
  },
  {
    id: 16,
    name: "Pastel de la Luz Dorada",
    image: "img/pastel_dorado.jpeg",
    description: "Dulce que brilla y alegra cada bocado.",
    price: 12,
    stock: 18,
  },
  {
    id: 17,
    name: "Sándwich del Campo Florido",
    image: "img/sandwich_campo.jpg",
    description: "Sándwich lleno de frescura campestre.",
    price: 6,
    stock: 22,
  },
  {
    id: 18,
    name: "Chocolates del Océano Azul",
    image: "img/chocolates_oceano.jpg",
    description: "Dulces con un sabor único de la brisa marina.",
    price: 11,
    stock: 15,
  },
  {
    id: 19,
    name: "Croissant de la Aurora",
    image: "img/croissant_aurora.jpg",
    description: "Croissant suave con colores del amanecer.",
    price: 8,
    stock: 30,
  },
  {
    id: 20,
    name: "Galletas del Fuego Sagrado",
    image: "./assets/galletas_fuego.jpeg",
    description: "Galletas con un toque especiado y atrevido.",
    price: 7,
    stock: 25,
  }, */
];
