const productos = [
  {
    id: 1,
    nombre: "Caramelos Ghibbbli",
    imagen: "img/caramelos.jpg",
    descripcion: "Caramelos varios.",
    precio: 10,
    stock: 20,
  },
  {
    id: 2,
    nombre: "Turron de Dragon",
    imagen: "img/patatas.jpg",
    descripcion: "Turron de chocolate.",
    precio: 5,
    stock: 50,
  },
  {
    id: 3,
    nombre: "Tarta del Bosque Encantado",
    imagen: "./assets/products/tarta_bosque.jpeg",
    descripcion: "Tarta mágica con ingredientes del bosque.",
    precio: 12,
    stock: 15,
  },
  {
    id: 4,
    nombre: "Helado del Valle Misterioso",
    imagen: "img/helado_valle.jpg",
    descripcion: "Helado suave con un toque de misterio.",
    precio: 8,
    stock: 25,
  },
  {
    id: 5,
    nombre: "Poción de Energía Solar",
    imagen: "img/pocion_solar.jpg",
    descripcion: "Bebida revitalizante hecha con rayos de sol.",
    precio: 9,
    stock: 30,
  },
  /* {
    id: 6,
    nombre: "Sopa de la Estrella Fugaz",
    imagen: "img/sopa_estrella.jpg",
    descripcion: "Caldo reconfortante inspirado en las estrellas.",
    precio: 7,
    stock: 20,
  },
  {
    id: 7,
    nombre: "Empanada de la Luna Llena",
    imagen: "img/empanada_luna.jpg",
    descripcion: "Empanada con un toque especial de noche mágica.",
    precio: 6,
    stock: 40,
  },
  {
    id: 8,
    nombre: "Caramelos del Arcoíris",
    imagen: "img/caramelos_arcoiris.jpg",
    descripcion: "Dulces coloridos que brillan al sol.",
    precio: 4,
    stock: 50,
  },
  {
    id: 9,
    nombre: "Pizza del Dragón Legendario",
    imagen: "img/pizza_dragon.jpg",
    descripcion: "Pizza con un sabor explosivo y aventurero.",
    precio: 15,
    stock: 10,
  },
  {
    id: 10,
    nombre: "Pan de las Montañas Nebulosas",
    imagen: "img/pan_montanas.jpg",
    descripcion: "Pan fresco con un aroma que inspira calma.",
    precio: 5,
    stock: 25,
  },
  {
    id: 11,
    nombre: "Té del Espíritu Serpentino",
    imagen: "img/te_espiritu.jpg",
    descripcion: "Infusión cálida con un toque de magia antigua.",
    precio: 6,
    stock: 35,
  },
  {
    id: 12,
    nombre: "Galletas del Espantapájaros",
    imagen: "img/galletas_espantapajaros.jpg",
    descripcion: "Galletas con un toque misterioso y divertido.",
    precio: 7,
    stock: 50,
  },
  {
    id: 13,
    nombre: "Zumo del Árbol Viviente",
    imagen: "img/zumo_arbol.jpg",
    descripcion: "Zumo fresco con sabores mágicos del bosque.",
    precio: 10,
    stock: 30,
  },
  {
    id: 14,
    nombre: "Bombones del Castillo Mágico",
    imagen: "./assets/bombones_castillo.jpeg",
    descripcion: "Chocolates con un diseño inspirado en castillos.",
    precio: 14,
    stock: 12,
  },
  {
    id: 15,
    nombre: "Refresco del Viento Silbador",
    imagen: "img/refresco_viento.jpg",
    descripcion: "Bebida gaseosa que refresca como una brisa.",
    precio: 9,
    stock: 20,
  },
  {
    id: 16,
    nombre: "Pastel de la Luz Dorada",
    imagen: "img/pastel_dorado.jpeg",
    descripcion: "Dulce que brilla y alegra cada bocado.",
    precio: 12,
    stock: 18,
  },
  {
    id: 17,
    nombre: "Sándwich del Campo Florido",
    imagen: "img/sandwich_campo.jpg",
    descripcion: "Sándwich lleno de frescura campestre.",
    precio: 6,
    stock: 22,
  },
  {
    id: 18,
    nombre: "Chocolates del Océano Azul",
    imagen: "img/chocolates_oceano.jpg",
    descripcion: "Dulces con un sabor único de la brisa marina.",
    precio: 11,
    stock: 15,
  },
  {
    id: 19,
    nombre: "Croissant de la Aurora",
    imagen: "img/croissant_aurora.jpg",
    descripcion: "Croissant suave con colores del amanecer.",
    precio: 8,
    stock: 30,
  },
  {
    id: 20,
    nombre: "Galletas del Fuego Sagrado",
    imagen: "./assets/galletas_fuego.jpeg",
    descripcion: "Galletas con un toque especiado y atrevido.",
    precio: 7,
    stock: 25,
  }, */
];
